language: cpp

compiler:
  - gcc
os: linux

dist: xenial

sudo: required

before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq libboost-all-dev flex bison coinor-* libwxgtk3.0-dev libgl1-mesa-dev libglu1-mesa-dev freeglut3-dev libglew-dev libpng-dev

install:
- make clean
- make all